# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

workflows:
  version: 2
  test_&_build:
    jobs:
      - test
      - docker_build:
          requires:
            - test
          filters:
            branches:
              only: master


version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
      - run: node_modules/.bin/codecov --token=$CODE_COV
  docker_build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
       - checkout
       - setup_remote_docker
       # Download and cache dependencies
       - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

       - run: yarn install

       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
       - run: yarn build 
       - run: docker build -t deniskondrachuk/react-app .
       - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
       - run: docker push deniskondrachuk/react-app
       - run: docker logout
